name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Print Rust version
        run: rustup show
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Print Rust version
        run: rustup show
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Nightly Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: component
        uses: actions-rs/components-nightly@v1
        with:
          target: x86_64-unknown-linux-gnu
          component: rustfmt
      - uses: hencrice/toolchain@e80da8a
        with:
            toolchain: ${{ steps.component.outputs.toolchain }}
            override: true
            component: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: ${{ steps.component.outputs.command }}
          args: --all -- --check

  clippy:
    name: Nightly Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: component
        uses: actions-rs/components-nightly@v1
        with:
          target: x86_64-unknown-linux-gnu
          component: clippy
      - uses: hencrice/toolchain@e80da8a
        with:
            toolchain: ${{ steps.component.outputs.toolchain }}
            override: true
            component: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: ${{ steps.component.outputs.command }}
          args: -- -D warnings

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features